swagger: "2.0"
info:
  title: "Sunglasses.io API"
  description: "API definition for Sunglasses.io"
  version: "1.0.0"
host: "localhost:3001"
basePath: "/api"
schemes:
- "http"
produces:
  - "application/json"
tags:
  - name: Brands
    description: "Access to Brands information."
  - name: Products
    description: "Access to Product information."
  - name: Cart
    description: "Operations for the shopping cart."
  - name: Login
    description: "Operations for user login."
paths:
  /brands:
    get:
      tags:
      - Brands
      summary: "Retrieve all sunglasses brands."
      description: |
        This endpoint returns information on all brands.
      parameters:
      - name: query
        in: query
        description: "Search query for search bar"
        required: false
        type: string
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Brands"
  /brands/{brandId}/products:
    get:
      tags:
      - Brands
      summary: "Sunglasses by brand id"
      description: "This endpoint returns all sunglasses by a specific brand id."
      parameters:
      - name: "brandId"
        in: "path"
        description: "Id of brand to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Brands"
        400:
          description: "Invalid brand id supplied"
        404:
          description: "Brand id not found"
  /products:
    get:
      tags: 
        - Products
      summary: "Sunglasses products"
      description: |
        "This endpoint returns information on all Sunglasses.io products."
      parameters:
      - name: query
        in: query
        description: "Search query for search bar"
        required: false
        type: string
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Products"
  /login:
    post:
      tags:
        - Login
      summary: "User login to the store."
      description: ''
      parameters:
        - name: email
          in: header
          description: "User email address"
          required: true
          type: string
        - name: password
          in: header
          description: "User password"
          required: true
          type: string
      responses:
        '200':
          description: "OK"
        '401':
          description: "Invalid username or password."
  /me/cart:
    get:
      tags:
         - Cart
      summary: "User cart"
      description: |
        "This endpoint returns information on all items in the user cart."
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: object
              properties:
                productId:
                  type: number
                quantity:
                 type: number
        401:
          description: "Not authorized. User must login to view cart."
    post:
      tags:
         - Cart
      summary: "This endpoint allows updating of cart contents."
      description: ''
      parameters:
        - name: productId
          in: header
          description: "Id of the item to update"
          required: true
          type: string
        - name: quantity
          in: header
          description: "Quantity to update the item to."
          required: true
          type: string
      responses:
        '200':
          description: "Update successful"
        '400':
          description: "Invalid product id or quantity."
        '401':
          description: "Not authorized. User must login to update cart."
  /me/cart/{productId}:
    delete:
      tags:
         - Cart
      summary: "Delete cart item by product id."
      description: ""
      parameters:
        - name: "productId"
          in: path
          description: "ID of the item that needs to be deleted"
          required: true
          type: string
      responses:
        '200':
          description: "successful operation."
        '400':
          description: "Invalid product id."
        '401':
          description: "Not authorized. User must login to update cart."
    post:
      tags:
         - Cart
      summary: "Add an item to the cart by product id"
      description: ''
      parameters:
        - name: "productId"
          in: path
          description: "Item id to add to cart"
          required: true
          type: string
      responses:
        '200':
          description: "successful operation."
        '400':
          description: "Invalid product id or quantity."
        '401':
          description: "Not authorized. User must login to update cart."
definitions:
  Brands:
    type: object
    properties:
      id:
        type: string
        description: "Brand id value"
      name:
        type: string
        description: "Brand name"
  Products:
    type: object
    properties:
      id:
        type: string
        description: "Product id value"
      categoryId:
        type: string
        description: "Category id value"
      name:
        type: string
        description: "Product name"
      description:
        type: string
        description: "Product description"
      price:
        type: number
        description: "Price"
      imageUrls:
        type: array
        items:
          type: string
          description: "Array of product image urls"
  Users:
    type: object
    properties:
      gender:
        type: string
      cart:
        type: array
        items:
          type: object
          properties:
            productId:
              type: number
            quantity:
              type: number
      name:
        type: object
        properties:
          title:
            type: string
          first:
            type: string
          last:
            type: string
      location:
        type: object
        properties:
          street:
            type: string
          city:
            type: string
          state:
            type: string
          postcode:
            type: number
      email:
        type: string
      login:
        type: object
        properties:
          username:
            type: string
          password:
            type: string
          salt:
            type: string
          md5:
            type: string
          sha1:
            type: string
          sha256:
            type: string
      dob:
        type: string
      registered:
        type: string
      phone:
        type: string
      cell:
        type: string
      picture:
        type: object
        properties:
          large:
            type: string
          medium:
            type: string
          small:
            type: string
      nat:
        type: string